// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EveOfMidnight.Core.Models
{
    public partial class AbilityLevel
    {
        public AbilityLevel()
        {
            Abilities = new HashSet<Ability>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int DotsToDice { get; set; }

        public virtual ICollection<Ability> Abilities { get; set; }
    }
}