// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace EveOfMidnight.Core.Models;

    public partial class Ability
    {
        public Guid Id { get; set; }
        public int AbilityLevelId { get; set; }
        public Guid SkillId { get; set; }
        public Guid TraitId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Dots { get; set; }
        public bool IsRaceDependent { get; set; }
        public bool IsItemDependent { get; set; }
        public bool IsMagicDependent { get; set; }

        public virtual AbilityLevel AbilityLevel { get; set; }
        public virtual Skill Skill { get; set; }
        public virtual Trait Trait { get; set; }
    }
