// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EveOfMidnight.Core.Models
{
    public partial class Beastiary
    {
        public Guid Id { get; set; }
        public Guid Class { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsMagical { get; set; }
        public bool IsCapturable { get; set; }
        public bool IsLegendary { get; set; }
        public string Attacks { get; set; }
    }
}