// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EveOfMidnight.Core.Models
{
    public partial class CharacterDetail
    {
        public Guid Id { get; set; }
        public Guid PlayerCharacterId { get; set; }
        public int RaceId { get; set; }
        public int FateId { get; set; }
        public int BoundId { get; set; }
        public int FocusId { get; set; }
        public int Morality { get; set; }
        public int Ambition { get; set; }
        public int Health { get; set; }
        public int WeightLimit { get; set; }
    }
}