// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EveOfMidnight.Core.Models
{
    public partial class ItemType
    {
        public ItemType()
        {
            ItemSubTypes = new HashSet<ItemSubType>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }

        public virtual ICollection<ItemSubType> ItemSubTypes { get; set; }
    }
}