// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EveOfMidnight.Core.Models
{
    public partial class PlayerCharacter
    {
        public Guid Id { get; set; }
        public Guid OwnedById { get; set; }
        public Guid CharacterDetailId { get; set; }
        public string Name { get; set; }
        public string Backstory { get; set; }
    }
}