// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EveOfMidnight.Core.Models
{
    public partial class RaceSkill
    {
        public Guid RaceId { get; set; }
        public Guid SkillId { get; set; }

        public virtual Race Race { get; set; }
        public virtual Skill Skill { get; set; }
    }
}