// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EveOfMidnight.Core.Models
{
    public partial class Skill
    {
        public Skill()
        {
            Abilities = new HashSet<Ability>();
            InverseBaseSkill = new HashSet<Skill>();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Dots { get; set; }
        public bool IsBaseSkill { get; set; }
        public Guid? BaseSkillId { get; set; }

        public virtual Skill BaseSkill { get; set; }
        public virtual ICollection<Ability> Abilities { get; set; }
        public virtual ICollection<Skill> InverseBaseSkill { get; set; }
    }
}