// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EveOfMidnight.Core.Models
{
    public partial class Spell
    {
        public Guid Id { get; set; }
        public int FocusId { get; set; }
        public Guid MagicSchoolId { get; set; }
        public int SpellRankId { get; set; }
        public bool IsRitual { get; set; }
        public int ManaCost { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int CastingTime { get; set; }
        public string CastingTimeDescription { get; set; }
        public int Duration { get; set; }
        public string DurationDescription { get; set; }

        public virtual Focus Focus { get; set; }
        public virtual MagicSchool MagicSchool { get; set; }
        public virtual SpellRank SpellRank { get; set; }
    }
}