// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EveOfMidnight.Core.Models
{
    public partial class Trait
    {
        public Trait()
        {
            Abilities = new HashSet<Ability>();
            InverseBaseTrait = new HashSet<Trait>();
        }

        public Guid Id { get; set; }
        public int TraitCategoryId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsBaseTrait { get; set; }
        public Guid? BaseTraitId { get; set; }

        public virtual Trait BaseTrait { get; set; }
        public virtual TraitCategory TraitCategory { get; set; }
        public virtual ICollection<Ability> Abilities { get; set; }
        public virtual ICollection<Trait> InverseBaseTrait { get; set; }
    }
}