// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EveOfMidnight.Data.Contexts;
using EveOfMidnight.Core.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace EveOfMidnight.Data.Contexts.Configurations
{
    public partial class AbilityConfiguration : IEntityTypeConfiguration<Ability>
    {
        public void Configure(EntityTypeBuilder<Ability> entity)
        {
            entity.HasIndex(e => e.AbilityLevelId, "IX_Abilities_AbilityLevelId");

            entity.HasIndex(e => e.SkillId, "IX_Abilities_SkillId");

            entity.HasIndex(e => e.TraitId, "IX_Abilities_TraitId");

            entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");

            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(1000);

            entity.Property(e => e.Dots).HasDefaultValueSql("((5))");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.AbilityLevel)
                .WithMany(p => p.Abilities)
                .HasForeignKey(d => d.AbilityLevelId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Abilities_AbilityLevel");

            entity.HasOne(d => d.Skill)
                .WithMany(p => p.Abilities)
                .HasForeignKey(d => d.SkillId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Abilities_Skills");

            entity.HasOne(d => d.Trait)
                .WithMany(p => p.Abilities)
                .HasForeignKey(d => d.TraitId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Abilities_Trait");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Ability> entity);
    }
}
