// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EveOfMidnight.Data.Contexts;
using EveOfMidnight.Core.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace EveOfMidnight.Data.Contexts.Configurations
{
    public partial class PlayerSpellConfiguration : IEntityTypeConfiguration<PlayerSpell>
    {
        public void Configure(EntityTypeBuilder<PlayerSpell> entity)
        {
            entity.HasNoKey();

            entity.HasIndex(e => e.PlayerCharacterId, "IX_PlayerSpells_PlayerCharacterId");

            entity.HasIndex(e => e.SpellId, "IX_PlayerSpells_SpellId");

            entity.HasOne(d => d.PlayerCharacter)
                .WithMany()
                .HasForeignKey(d => d.PlayerCharacterId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PlayerSpells_PlayerCharacters");

            entity.HasOne(d => d.Spell)
                .WithMany()
                .HasForeignKey(d => d.SpellId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PlayerSpells_Spells");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PlayerSpell> entity);
    }
}
