// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EveOfMidnight.Data.Contexts;
using EveOfMidnight.Core.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace EveOfMidnight.Data.Contexts.Configurations
{
    public partial class PlayerTraitConfiguration : IEntityTypeConfiguration<PlayerTrait>
    {
        public void Configure(EntityTypeBuilder<PlayerTrait> entity)
        {
            entity.HasNoKey();

            entity.Property(e => e.Dots).HasDefaultValueSql("((0))");

            entity.HasOne(d => d.PlayerCharacter)
                .WithMany()
                .HasForeignKey(d => d.PlayerCharacterId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PlayerTraits_PlayerCharacters");

            entity.HasOne(d => d.Trait)
                .WithMany()
                .HasForeignKey(d => d.TraitId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PlayerTraits_Traits");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PlayerTrait> entity);
    }
}
