// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EveOfMidnight.Data.Contexts;
using EveOfMidnight.Core.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace EveOfMidnight.Data.Contexts.Configurations
{
    public partial class SpellConfiguration : IEntityTypeConfiguration<Spell>
    {
        public void Configure(EntityTypeBuilder<Spell> entity)
        {
            entity.HasIndex(e => e.FocusId, "IX_Spells_FocuslId");

            entity.HasIndex(e => e.MagicSchoolId, "IX_Spells_MagicSchoolId");

            entity.HasIndex(e => e.ManaCost, "IX_Spells_ManaCost");

            entity.HasIndex(e => e.SpellRankId, "IX_Spells_SpellRankId");

            entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");

            entity.Property(e => e.CastingTimeDescription)
                .IsRequired()
                .HasMaxLength(20);

            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(1000);

            entity.Property(e => e.DurationDescription)
                .IsRequired()
                .HasMaxLength(20);

            entity.Property(e => e.ManaCost).HasDefaultValueSql("((7))");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Focus)
                .WithMany(p => p.Spells)
                .HasForeignKey(d => d.FocusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Spells_Focus");

            entity.HasOne(d => d.MagicSchool)
                .WithMany(p => p.Spells)
                .HasForeignKey(d => d.MagicSchoolId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("Fk_Spells_MagicSchools");

            entity.HasOne(d => d.SpellRank)
                .WithMany(p => p.Spells)
                .HasForeignKey(d => d.SpellRankId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Spells_SpellRanks");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Spell> entity);
    }
}
