// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EveOfMidnight.Data.Contexts;
using EveOfMidnight.Core.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace EveOfMidnight.Data.Contexts.Configurations
{
    public partial class TraitConfiguration : IEntityTypeConfiguration<Trait>
    {
        public void Configure(EntityTypeBuilder<Trait> entity)
        {
            entity.HasIndex(e => e.BaseTraitId, "IX_Traits_BaseTraitId");

            entity.HasIndex(e => e.TraitCategoryId, "IX_Traits_TraitCategoryId");

            entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");

            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(1000);

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.BaseTrait)
                .WithMany(p => p.InverseBaseTrait)
                .HasForeignKey(d => d.BaseTraitId)
                .HasConstraintName("FK_Traits_BaseTraitId");

            entity.HasOne(d => d.TraitCategory)
                .WithMany(p => p.Traits)
                .HasForeignKey(d => d.TraitCategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Traits_TraitCategory");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Trait> entity);
    }
}
